name: Update ispappLibrary.rsc

on:
  push:
    branches:
      - karim

jobs:
  update_scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Generate and update ispappLibrary.rsc
      run: node .github/scripts/updateScripts.js
    
    - name: Get last commit message
      id: commit_msg
      run: |
        echo "LAST_COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
    
    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
        file-path: ispapp*.rsc
        branch: karim
        commit-msg: ispapp agent scripts updated <${{ env.LAST_COMMIT_MSG }}>
        github-token: ${{ secrets.ISPAPPTOKEN }}
